apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: stocktrader
  description: Stock Trader
spec:
  cd  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: API
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: messaging-ejb/src/main/generated/openapi/openapi.yaml
metadata:
  name: messaging-api
  tags:
    - java
    - openliberty
---
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  # the type must be a service for the CI/CD tab to render unless you change the
  # EntityPage.tsx to use a ComponentType of `application`
  type: service
  lifecycle: production
  system: stocktrader
  owner: guests
  providesApis:
    - messaging-api
  dependsOn:
    - component:default/notification-client-config
metadata:
  name: messaging
  labels:
    app.kubernetes.io/name: messaging
    app.kubernetes.io/version: 1.0-SNAPSHOT
  annotations:
    backstage.io/source-location: url:https://github.com/IBMStockTrader/messaging
    github.com/project-slug: IBMStockTrader/messaging
  tags:
    - java
    - openliberty
